import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

// Copy styles.css from src to root
if (prod) {
	await context.rebuild();
	try {
		copyFileSync('src/styles.css', 'styles.css');
		console.log('✓ Copied styles.css');
	} catch (e) {
		console.error('Failed to copy styles.css:', e);
	}
	process.exit(0);
} else {
	// Copy styles in dev mode too
	try {
		copyFileSync('src/styles.css', 'styles.css');
	} catch (e) {
		// Ignore in dev mode
	}
	await context.watch();
}